export const ACRONYMS: Record<string, string> = {
  luanda: 'LA',
  benguela: 'BE',
  huila: 'HU',
  huambo: 'HA',
  namibe: 'NA',
  malanje: 'MA',
  bie: 'BI',
  cuanza_sul: 'CS',
  cuanza_norte: 'CN',
  zaire: 'ZA',
  cabinda: 'CA',
  uige: 'UI',
  lunda_norte: 'LN',
  lunda_sul: 'LS',
  moxico: 'MO',
  cunene: 'CU',
  cuando_cubango: 'CC',
  bengo: 'BG',
} as const;
